import { api } from "./api";
import type { PedidoFull, PropostaFull } from "./api"; export type DemoOrderStatus = | "pending" | "active" | "completed" | "work_completed" | "work_completed_confirmed" | "cancelled"; export type DemoProposalStatus = "pending" | "accepted" | "rejected";
export type ReviewType = "client" | "provider"; export interface DemoOrder { id: number; clientUserId: number; clientName: string; clientEmail: string; clientPhone: string; clientPhoto?: string; title: string; category: string; status: DemoOrderStatus; description: string; location: string; date: string; proposals: number; budget: string; acceptedProposalId?: number; clientFinishedConfirmed?: boolean; providerFinishedConfirmed?: boolean; hasSentProposal?: boolean; cancelledAt?: string; cancellationReason?: string;
} export interface DemoProposal { id: number; orderId: number; providerUserId: number; providerName: string; providerPhoto?: string; serviceTitle: string; clientName: string; myPrice: string; status: DemoProposalStatus; sentDate: string; description: string; deliveryTime: string; competitors: number;
} export interface DemoReview { id: number; orderId: number; proposalId: number; fromUserId: number; toUserId: number; fromUserType: ReviewType; toUserName: string; toUserPhoto?: string; serviceTitle: string; rating: number; comment: string; date: string;
} function formatCurrentDate(): string { return new Intl.DateTimeFormat("pt-BR").format(new Date());
}
// ---------------------------------------------------------------------------
// Backend ↔ Frontend mappers
// ---------------------------------------------------------------------------
function mapBackendStatusToDemo( status: string, clienteConfirmed?: boolean, prestadorConfirmed?: boolean
): DemoOrderStatus { switch (status?.toUpperCase()) { case "ABERTO": return "pending"; case "EM_ANDAMENTO": if (clienteConfirmed && prestadorConfirmed) return "work_completed_confirmed"; if (clienteConfirmed || prestadorConfirmed) return "work_completed"; return "active"; case "CONCLUIDO": return "work_completed_confirmed"; case "CANCELADO": return "cancelled"; default: return "pending"; }
} function mapProposalStatus(status: string): DemoProposalStatus { switch (status?.toUpperCase()) { case "ACEITA": return "accepted"; case "RECUSADA": return "rejected"; default: return "pending"; }
} function formatPrice(value: number | undefined | null): string { if (!value) return "A combinar"; return `R$ ${Number(value).toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2, })}`;
} function parseCurrencyToNumber(value: string): number { const normalized = value.replace(/[^\d,.-]/g, "").replace(".", "").replace(",", "."); const parsed = Number(normalized); return Number.isFinite(parsed) ? parsed : 0;
} function formatBackendDate(isoDate: string | undefined): string {
  if (!isoDate) return formatCurrentDate();
  try {
    return new Intl.DateTimeFormat("pt-BR").format(new Date(isoDate));
  } catch {
    return formatCurrentDate();
  }
}

function pedidoToDemoOrder(p: PedidoFull, proposals: DemoProposal[] = []): DemoOrder { const acceptedProposal = proposals.find((pr) => pr.status === "accepted"); return { id: p.id, clientUserId: p.usuario?.id ?? 0, clientName: p.contatoNome || p.usuario?.nome || "", clientEmail: p.contatoEmail || p.usuario?.email || "", clientPhone: p.contatoTelefone || p.usuario?.telefone || "", clientPhoto: p.usuario?.foto, title: p.titulo, category: p.servico?.categoria?.nome || p.servico?.titulo || "", status: mapBackendStatusToDemo( p.status, p.clienteConfirmouConclusao, p.prestadorConfirmouConclusao ), description: p.descricao, location: p.localizacao, date: formatBackendDate(p.dataCriacao), proposals: proposals.length, budget: acceptedProposal ? acceptedProposal.myPrice : "A combinar", acceptedProposalId: acceptedProposal?.id, clientFinishedConfirmed: p.clienteConfirmouConclusao ?? false, providerFinishedConfirmed: p.prestadorConfirmouConclusao ?? false, };
} function propostaToDemoProposal(pr: PropostaFull, totalForOrder?: number): DemoProposal { return { id: pr.id, orderId: pr.pedido?.id ?? 0, providerUserId: pr.prestador?.id ?? 0, providerName: pr.prestador?.nome || "Prestador", providerPhoto: pr.prestador?.foto, serviceTitle: pr.pedido?.titulo || "", clientName: pr.pedido?.usuario?.nome || "", myPrice: formatPrice(pr.precoProposto), status: mapProposalStatus(pr.status), sentDate: formatBackendDate(pr.dataCriacao), description: pr.mensagem || "", deliveryTime: pr.prazoEntrega || "A combinar", competitors: Math.max(0, (totalForOrder ?? 1) - 1), };
}
// ---------------------------------------------------------------------------
// Public API — all async, all from backend
// ---------------------------------------------------------------------------

export async function getClientOrders(clientUserId: number): Promise<DemoOrder[]> { const pedidos = await api.getPedidosByUser(clientUserId); if (!pedidos.length) return []; const proposalArrays = await Promise.all( pedidos.map((p) => api.getPropostasByPedido(p.id).catch(() => [] as PropostaFull[])) ); return pedidos .map((pedido, i) => { const proposals = proposalArrays[i].map((pr) => propostaToDemoProposal(pr)); return pedidoToDemoOrder(pedido, proposals); }) .sort((a, b) => b.id - a.id);
} export async function getAvailableOrdersForProvider(providerUserId: number): Promise<DemoOrder[]> { const pedidos = await api.getPedidosAbertos(providerUserId); if (!pedidos.length) return []; const [proposalArrays, myPropostas] = await Promise.all([ Promise.all( pedidos.map((p) => api.getPropostasByPedido(p.id).catch(() => [] as PropostaFull[])) ), api.getPropostasByPrestador(providerUserId).catch(() => [] as PropostaFull[]), ]); const myOrderIds = new Set(myPropostas.map((pr) => pr.pedido?.id ?? 0)); return pedidos .map((pedido, i) => { const proposals = proposalArrays[i].map((pr) => propostaToDemoProposal(pr)); return { ...pedidoToDemoOrder(pedido, proposals), hasSentProposal: myOrderIds.has(pedido.id), }; }) .sort((a, b) => b.id - a.id);
} export async function getProviderProposals(providerUserId: number): Promise<DemoProposal[]> { const propostas = await api.getPropostasByPrestador(providerUserId); return propostas .map((pr) => propostaToDemoProposal(pr)) .sort((a, b) => b.id - a.id);
} export async function getOrderProposals(orderId: number): Promise<DemoProposal[]> { const propostas = await api.getPropostasByPedido(orderId); return propostas .map((pr) => propostaToDemoProposal(pr, propostas.length)) .sort((a, b) => b.id - a.id);
} export async function hasProposalFromProvider( orderId: number, providerUserId: number
): Promise<boolean> { const propostas = await api .getPropostasByPedido(orderId) .catch(() => [] as PropostaFull[]); return propostas.some((pr) => (pr.prestador?.id ?? 0) === providerUserId);
} export async function getOrderById(orderId: number): Promise<DemoOrder | null> { try { const pedido = await api.getPedidoById(orderId); const propostas = await api .getPropostasByPedido(orderId) .catch(() => [] as PropostaFull[]); return pedidoToDemoOrder(pedido, propostas.map((pr) => propostaToDemoProposal(pr))); } catch { return null; }
} export async function deleteDemoOrder(orderId: number, clientUserId: number): Promise<void> { const order = await getOrderById(orderId); if (!order) { throw new Error("Pedido não encontrado."); } if (order.clientUserId !== clientUserId) { throw new Error("Você não tem permissão para excluir este pedido."); } await api.deletePedido(orderId);
} export async function createDemoOrder(input: { clientUserId: number; clientName: string; clientEmail: string; clientPhone: string; clientPhoto?: string; title: string; category: string; description: string; location: string;
}): Promise<DemoOrder> { const created = await api.createPedidoBackend({ usuario: { id: input.clientUserId }, titulo: input.title, descricao: input.description, localizacao: input.location, status: "ABERTO", contatoNome: input.clientName, contatoEmail: input.clientEmail, contatoTelefone: input.clientPhone, }); return pedidoToDemoOrder(created, []);
} export async function submitDemoProposal(input: { orderId: number; providerUserId: number; providerName: string; providerPhoto?: string; price: string; description: string; deliveryTime: string;
}): Promise<DemoProposal> { const pedido = await getOrderById(input.orderId); if (!pedido) { throw new Error("Pedido não encontrado."); } if (pedido.clientUserId === input.providerUserId) { throw new Error("Você não pode enviar proposta para o próprio pedido."); } const created = await api.createPropostaBackend({ pedido: { id: input.orderId }, prestador: { id: input.providerUserId }, precoProposto: parseCurrencyToNumber(input.price), status: "AGUARDANDO", mensagem: input.description, }); return propostaToDemoProposal(created);
} export async function acceptDemoProposal( _orderId: number, proposalId: number
): Promise<DemoProposal> { const accepted = await api.aceitarProposta(proposalId); return propostaToDemoProposal(accepted);
} export async function updateDemoProposal(input: { proposalId: number; providerUserId: number; price: string; description: string; deliveryTime: string;
}): Promise<DemoProposal> { const updated = await api.updateProposta(input.proposalId, { precoProposto: parseCurrencyToNumber(input.price), mensagem: input.description, status: "AGUARDANDO", }); return propostaToDemoProposal(updated);
} export async function deleteDemoProposal( proposalId: number, providerUserId: number
): Promise<void> { const myProposals = await getProviderProposals(providerUserId); const isOwner = myProposals.some((proposal) => proposal.id === proposalId); if (!isOwner) { throw new Error("Você não tem permissão para excluir esta proposta."); } await api.deleteProposta(proposalId);
} export async function confirmWorkFinished(orderId: number, userId: number): Promise<DemoOrder> { const order = await getOrderById(orderId); if (!order) throw new Error("Pedido não encontrado."); const tipo = order.clientUserId === userId ? "CLIENTE" : "PRESTADOR"; const updatedPedido = await api.confirmarConclusao(orderId, tipo); const propostas = await api .getPropostasByPedido(orderId) .catch(() => [] as PropostaFull[]); return pedidoToDemoOrder(updatedPedido, propostas.map((pr) => propostaToDemoProposal(pr)));
} export async function submitReview(input: { orderId: number; proposalId: number; fromUserId: number; toUserId: number; fromUserType: ReviewType; toUserName: string; toUserPhoto?: string; serviceTitle: string; rating: number; comment: string;
}): Promise<DemoReview> { const order = await getOrderById(input.orderId); if (!order) throw new Error("Pedido não encontrado."); const readyToReview = order.status === "work_completed_confirmed" || (order.clientFinishedConfirmed === true && order.providerFinishedConfirmed === true); if (!readyToReview) throw new Error("Você só pode avaliar após ambos confirmarem o término."); const jaAvaliou = await api.jaAvaliou(input.fromUserId, input.toUserId).catch(() => false); if (jaAvaliou) throw new Error("Você já avaliou este serviço."); const saved = await api.createAvaliacao({ avaliador: { id: input.fromUserId }, avaliado: { id: input.toUserId }, nota: input.rating, comentario: input.comment, data: new Date().toISOString(), }); return { id: saved.id, orderId: input.orderId, proposalId: input.proposalId, fromUserId: input.fromUserId, toUserId: input.toUserId, fromUserType: input.fromUserType, toUserName: input.toUserName, toUserPhoto: input.toUserPhoto, serviceTitle: input.serviceTitle, rating: input.rating, comment: input.comment, date: formatCurrentDate(), };
} export async function getPendingReviews( userId: number, userType: ReviewType
): Promise< Array<{ id: number; service: string; professional: { name: string; photo?: string }; completedDate: string; price: string; orderId: number; proposalId: number; toUserId: number; }>
> { let completedOrders: DemoOrder[]; if (userType === "client") { const orders = await getClientOrders(userId); completedOrders = orders.filter( (o) => o.status === "work_completed_confirmed" || (o.clientFinishedConfirmed === true && o.providerFinishedConfirmed === true) ); } else { const proposals = await getProviderProposals(userId); const accepted = proposals.filter((p) => p.status === "accepted"); const orderIds = [...new Set(accepted.map((p) => p.orderId))]; const fetched = await Promise.all(orderIds.map((id) => getOrderById(id).catch(() => null))); completedOrders = fetched.filter( (o): o is DemoOrder => o !== null && (o.status === "work_completed_confirmed" || (o.clientFinishedConfirmed === true && o.providerFinishedConfirmed === true)) ); } const pendingChecks = await Promise.all( completedOrders.map(async (order) => { if (userType === "client") { const proposals = await getOrderProposals(order.id).catch(() => [] as DemoProposal[]); const acc = proposals.find((p) => p.status === "accepted"); if (!acc) return null; const jaAvaliou = await api.jaAvaliou(userId, acc.providerUserId).catch(() => false); if (jaAvaliou) return null; return { id: order.id, service: order.title, professional: { name: acc.providerName, photo: acc.providerPhoto }, completedDate: order.date, price: order.budget, orderId: order.id, proposalId: acc.id, toUserId: acc.providerUserId, }; } else { const jaAvaliou = await api.jaAvaliou(userId, order.clientUserId).catch(() => false); if (jaAvaliou) return null; return { id: order.id, service: order.title, professional: { name: order.clientName, photo: order.clientPhoto }, completedDate: order.date, price: order.budget, orderId: order.id, proposalId: order.acceptedProposalId ?? 0, toUserId: order.clientUserId, }; } }) ); return pendingChecks.filter( ( item ): item is { id: number; service: string; professional: { name: string; photo?: string }; completedDate: string; price: string; orderId: number; proposalId: number; toUserId: number; } => item !== null );
} export async function getGivenReviews(userId: number): Promise< Array<{ id: number; orderId: number; service: string; professional: { name: string; photo?: string }; rating: number; comment: string; date: string; }>
> { const avaliacoes = await api.getAvaliacoesByAvaliador(userId).catch(() => []); return avaliacoes.map((a) => ({ id: a.id, orderId: 0, service: a.avaliado?.nome ?? "Serviço", professional: { name: a.avaliado?.nome ?? "Profissional", photo: a.avaliado?.foto }, rating: a.nota, comment: a.comentario ?? "", date: a.data ? new Intl.DateTimeFormat("pt-BR").format(new Date(a.data)) : formatCurrentDate(), }));
} export async function getOrderReviewsStatus(orderId: number): Promise<{ clientReviewGiven: boolean; providerReviewGiven: boolean;
}> { const order = await getOrderById(orderId); if (!order) return { clientReviewGiven: false, providerReviewGiven: false }; const propostas = await api .getPropostasByPedido(orderId) .catch(() => [] as PropostaFull[]); const acceptedProposta = propostas.find((p) => p.status?.toUpperCase() === "ACEITA"); const providerUserId = acceptedProposta?.prestador?.id ?? 0; const [clientReviewGiven, providerReviewGiven] = await Promise.all([ providerUserId > 0 ? api.jaAvaliou(order.clientUserId, providerUserId).catch(() => false) : Promise.resolve(false), providerUserId > 0 && order.clientUserId > 0 ? api.jaAvaliou(providerUserId, order.clientUserId).catch(() => false) : Promise.resolve(false), ]); return { clientReviewGiven, providerReviewGiven };
} export async function getAverageRating(userId: number): Promise<{ rating: number; count: number }> { try { const data = await api.getRatingMedia(userId); return { rating: data.media, count: data.total }; } catch { return { rating: 0, count: 0 }; }
}
// No-op: user data comes from backend, no localStorage sync needed

export function syncDemoUserReferences(_user: { id: number; nome: string; email: string; telefone?: string; foto?: string;
}): void { // noop
} 