const API_BASE = "/api/ticket"; export interface SupportTicket { id: string; userId: number; userName: string; email: string; subject: string; message: string; category: "bug" | "duvida" | "sugestao" | "pagamento" | "outro"; status: "aberto" | "respondido" | "fechado"; createdAt: string; responses: SupportResponse[];
} export interface SupportResponse { id: string; ticketId: string; respondedAt: string; responder: string; response: string;
} interface BackendTicket { id: number; usuario: { id: number; nome?: string; email?: string }; assunto: string; mensagem: string; categoria: string; status: string; criadoEm: string; respostas?: BackendResposta[];
} interface BackendResposta { id: number; respondente: string; resposta: string; respondidoEm: string;
} function mapTicket(t: BackendTicket): SupportTicket { return { id: String(t.id), userId: t.usuario.id, userName: t.usuario.nome ?? `Usuário #${t.usuario.id}`, email: t.usuario.email ?? "", subject: t.assunto, message: t.mensagem, category: t.categoria as SupportTicket["category"], status: t.status as SupportTicket["status"], createdAt: t.criadoEm, responses: (t.respostas ?? []).map((r) => ({ id: String(r.id), ticketId: String(t.id), respondedAt: r.respondidoEm, responder: r.respondente, response: r.resposta, })), };
} async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> { const res = await fetch(`${API_BASE}${path}`, { headers: { "Content-Type": "application/json", ...options?.headers }, ...options, }); if (!res.ok) { const text = await res.text().catch(() => ""); throw new Error(text || `Erro ${res.status}`); } if (res.status === 204) return undefined as T; return res.json() as Promise<T>;
} export async function createSupportTicket( userId: number, _userName: string, _email: string, subject: string, message: string, category: SupportTicket["category"]
): Promise<SupportTicket> { const ticket = await apiFetch<BackendTicket>("", { method: "POST", body: JSON.stringify({ usuarioId: userId, assunto: subject, mensagem: message, categoria: category }), }); return mapTicket(ticket);
} export async function getUserTickets(userId: number): Promise<SupportTicket[]> { const tickets = await apiFetch<BackendTicket[]>(`/usuario/${userId}`); return tickets.map(mapTicket);
} export async function getTicketById(ticketId: string): Promise<SupportTicket | null> { try { const ticket = await apiFetch<BackendTicket>(`/${ticketId}`); return mapTicket(ticket); } catch { return null; }
} export async function addResponseToTicket( ticketId: string, response: string
): Promise<SupportResponse> { const r = await apiFetch<BackendResposta>(`/${ticketId}/resposta`, { method: "POST", body: JSON.stringify({ resposta: response }), }); return { id: String(r.id), ticketId, respondedAt: r.respondidoEm, responder: r.respondente, response: r.resposta, };
} export async function closeTicket(ticketId: string, userId: number): Promise<void> { await apiFetch(`/${ticketId}/fechar`, { method: "PUT", body: JSON.stringify({ usuarioId: userId }), });
} export async function getOpenTicketsCount(userId: number): Promise<number> { const tickets = await getUserTickets(userId); return tickets.filter((t) => t.status === "aberto").length;
} 